name: Zappa Deploy

on:
  push:
    branches:
      - main
      - dev
      - staging
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Only if using temporary credentials
        run: |
          echo "Configuring boto3 session..."
          source venv/bin/activate
          python -c "import boto3; boto3.setup_default_session(aws_access_key_id='$AWS_ACCESS_KEY_ID', aws_secret_access_key='$AWS_SECRET_ACCESS_KEY', aws_session_token='$AWS_SESSION_TOKEN', region_name='us-east-1')"
          echo "Boto3 session configured."

      - name: Set Zappa Environment based on branch
        id: set-env
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Deploy or Update with Zappa
        id: deploy-zappa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }} # Only if using temporary credentials

        run: |
          set -e
          source venv/bin/activate
          DEPLOY_OUTPUT=$(zappa update $BRANCH_NAME || zappa deploy $BRANCH_NAME)
          LAST_LINE=$(echo "$DEPLOY_OUTPUT" | tail -n 1)
          API_URL=$(echo "$LAST_LINE" | grep -oP 'https://\S+amazonaws.com/\S+')
          API_URL_WITH_PATH="${API_URL}/upload"
          echo "API_URL_WITH_PATH=$API_URL_WITH_PATH" >> $GITHUB_ENV

      - name: Send API URL to Slack
        run: |
          SLACK_WEBHOOK_URL="https://hooks.slack.com/services/${{ secrets.SLACK_TEAM_ID }}/${{ secrets.SLACK_CHANNEL_ID }}/${{ secrets.SLACK_TOKEN }}"
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"Your API is available at: $API_URL_WITH_PATH\"}" \
          $SLACK_WEBHOOK_URL

      - name: Notify on Success
        if: success()
        run: |
          echo "Deployment was successful for branch $BRANCH_NAME!"
          echo "Your API is available at: ${{ env.API_URL_WITH_PATH }}"
