name: Zappa Deploy

on:
  push:
    paths:
      - "zappa_settings.json"
      - "ChromeEXT/**"
      - "requirements.txt"
      - "app/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Configure AWS Credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          echo "Configuring boto3 session..."
          source venv/bin/activate
          python -c "import boto3; boto3.setup_default_session(aws_access_key_id='$AWS_ACCESS_KEY_ID', aws_secret_access_key='$AWS_SECRET_ACCESS_KEY', aws_session_token='$AWS_SESSION_TOKEN', region_name='$AWS_DEFAULT_REGION')"
          echo "Boto3 session configured."

      - name: Set Zappa Environment based on branch
        id: set-env
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Deploy or Update with Zappa
        id: deploy-zappa
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: |
          set -e
          source venv/bin/activate
          if zappa status $BRANCH_NAME; then
            # App is already deployed, so we'll update it
            echo "already_deployed=true" >> $GITHUB_ENV
            zappa update $BRANCH_NAME
          else
            # New deployment
            echo "already_deployed=false" >> $GITHUB_ENV
            DEPLOY_OUTPUT=$(zappa deploy $BRANCH_NAME)
            LAST_LINE=$(echo "$DEPLOY_OUTPUT" | tail -n 1)
            API_URL=$(echo "$LAST_LINE" | grep -oP 'https://\S+amazonaws.com/\S+')
            API_URL_WITH_PATH="${API_URL}/upload"
            echo "API_URL_WITH_PATH=$API_URL_WITH_PATH" >> $GITHUB_ENV
          fi

      - name: Send Slack Notification on New Deployment
        if: env.already_deployed == 'false'
        run: |
          SLACK_WEBHOOK_URL="https://hooks.slack.com/services/${{ secrets.SLACK_TEAM_ID }}/${{ secrets.SLACK_CHANNEL_ID }}/${{ secrets.SLACK_TOKEN }}"
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"A new API has been deployed and is available at: ${{ env.API_URL_WITH_PATH }}\"}" \
          $SLACK_WEBHOOK_URL
